spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pdp_online
    username: doston
    password: doston123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 100MB
